Backport the frame ancestors self switch to this plugin
zero-24/plg_system_httpheader pull request #26
Opened 2020-02-25 11:50 UTC by zero-24

Hi,

this is a backpot for the PR i made for the core version here: https://github.com/joomla/joomla-cms/pull/28066

@brianteeman @Sandra97 @YGomiero @jeckodevelopment @pe7er please send me your translations / suggestions for the new language string as a comment or [suggestion](https://haacked.com/archive/2019/06/03/suggested-changes/) to this PR so I can add it to this PR and the final release.

```
PLG_SYSTEM_HTTPHEADER_CONTENTSECURITYPOLICY_FRAME_ANCESTORS_SELF_ENABLED_DESC="Enable the CSP clickjacking protection frame-ancestors and only allow the origin 'self'. Please use the form below to allow origins other than 'self'."
```

Feel free to ping me on any questions.

2020-02-25 14:43 UTC, jeckodevelopment requested changes

2020-02-25 14:43 UTC, jeckodevelopment commented on language/it-IT/it-IT.plg_system_httpheader.ini
> +PLG_SYSTEM_HTTPHEADER_CONTENTSECURITYPOLICY_FRAME_ANCESTORS_SELF_ENABLED_DESC="Enable the CSP clickjacking protection frame-ancestors and only allow the origin 'self'. Please use the form below to al
Abilita la protezione CSP da clickjacking frame-ancestors e consenti solo l'origine 'self'. Utilizza il modulo sottostante per abilitare altre origini diverse da 'self'.

2020-02-25 14:44 UTC, jeckodevelopment commented
Hope that this way was correct :)

2020-02-25 15:14 UTC, Sandra97 commented
Activer la protection CSP frame-ancestors contre le détournement de clic et n'autoriser que l'origine "self". Veuillez utiliser le formulaire ci-dessous pour autoriser les origines autres que "self".

2020-02-25 19:10 UTC, pe7er commented
PLG_SYSTEM_HTTPHEADER_CONTENTSECURITYPOLICY_FRAME_ANCESTORS_SELF_ENABLED_DESC="Schakel de CSP clickjacking bescherming voor frame-ancestors in en sta alleen 'zelf' als bron toe. Gebruik het onderstaande formulier om andere bronnen dan 'zelf' toe te staan."

2020-02-27 17:16 UTC, zero-24 commented
Many thanks I have just committed the updated language strings and can do a release soon 👍 

ps @pe7er i have used `'self'` over your `'zelf'` as `'self'` is the actual value you set to the header.

2020-03-15 15:20 UTC, merged